name: 'Saplings - Theme recipe'
description: 'Configures Saplings Child theme and dependent modules and UI Bootstrap base theme.'
type: 'Site'
install:
  # Core.
  - help
  # Contrib.
  - block_class
  - ds
  - ds_extras
  - field_group
  - layout_options
  - menu_bootstrap_icon
  - saplings_child
  - twig_tweak
  - ui_patterns
  - ui_patterns_ds
  - ui_patterns_field_formatters
  - ui_patterns_field_group
  - ui_patterns_layouts
  - ui_patterns_library
  - ui_patterns_settings
  - ui_skins
  - ui_styles
  - ui_suite_bootstrap
config:
  strict: false
  import:
    # Only Display suite has config.
    ds: "*"
    # Import blocks that Stark does not automatically create below.
    saplings_child:
      - block.block.saplings_child_breadcrumbs
      - block.block.saplings_child_content
      - block.block.saplings_child_footer
      - block.block.saplings_child_help
      - block.block.saplings_child_mainnavigation
      - block.block.saplings_child_main_menu
      - block.block.saplings_child_messages
      - block.block.saplings_child_page_title
      - block.block.saplings_child_sitebranding_footer
  actions:
    # Allow Display Suite on fields and Layouts.
    ds.settings:
      simpleConfigUpdate:
        field_template: true
        ft-layout-builder: true
    # When a theme is enabled in Drupal, the blocks of the existing theme are
    # automaticaly duplicated. In our case, on minimal, the theme is Stark.
    # We set the blocks we don't want to false, and alter the config of the
    # blocks that were created.
    block.block.saplings_child_admin:
      setStatus: false
    block.block.saplings_child_branding:
      setRegion: navigation
      setWeight: 0
    block.block.saplings_child_local_actions:
      setRegion: header
      setWeight: 20
    block.block.saplings_child_local_tasks:
      setRegion: header
      setWeight: 10
    block.block.saplings_child_page_title:
      setStatus: true
      setRegion: content
      setWeight: -30
      simpleConfigUpdate:
        visibility.request_path.id: request_path
        visibility.request_path.negate: false
        visibility.request_path.pages: '/user/*'
    block.block.saplings_child_tools:
      setStatus: false
    # Set the default theme.
    system.theme:
      simpleConfigUpdate:
        default: saplings_child
    # Allow anonymous users to access patterns page.
    user.role.anonymous:
      createIfNotExists:
        id: anonymous
      grantPermission: 'access patterns page'
