name: 'Saplings - Theme'
description: 'Configures the base and child theme with dependencies.'
type: 'Site'
install:
  # Core.
  - help
  # Contrib.
  - block_class
  - ds
  - ds_extras
  - layout_options
  - menu_bootstrap_icon
  - saplings_child
  - ui_patterns
  - ui_patterns_ds
  - ui_patterns_field_formatters
  - ui_patterns_field_group
  - ui_patterns_layouts
  - ui_patterns_library
  - ui_patterns_settings
  - ui_skins
  - ui_styles
  - ui_suite_bootstrap
config:
  import:
    # Only Display suite has config.
    ds: "*"
    # Import blocks that Stark does not automatically create below.
    saplings_child:
      - block.block.saplings_child_banner_2.yml
      - block.block.saplings_child_banner.yml
      - block.block.saplings_child_breadcrumbs.yml
      - block.block.saplings_child_content.yml
      - block.block.saplings_child_footer.yml
      - block.block.saplings_child_help.yml
      - block.block.saplings_child_main_menu.yml
      - block.block.saplings_child_messages.yml
      - block.block.saplings_child_page_title.yml
      - block.block.saplings_child_social.yml
  actions:
    # Allow Display Suite on fields and Layouts.
    ds.settings:
      simple_config_update:
        field_template: true
        ft-layout-builder: true
    # When a theme is enabled in Drupal, the blocks of the existing theme are
    # automaticaly duplicated. In our case, on minimal, the theme is Stark.
    # We set the blocks we don't want to false, and alter the config of the
    # blocks that were created.
    block.block.saplings_child_admin:
      simple_config_update:
        status: false
    block.block.saplings_child_branding:
      simple_config_update:
        region: navigation
        weight: 0
    block.block.saplings_child_local_actions:
      simple_config_update:
        region: header
        weight: 20
    block.block.saplings_child_local_tasks:
      simple_config_update:
        region: header
        weight: 10
    block.block.saplings_child_page_title:
      simple_config_update:
        status: true
        region: content
        weight: -30
        visibility.request_path.id: request_path
        visibility.request_path.negate: false
        visibility.request_path.pages: '/user/*'
    block.block.saplings_child_tools:
      simple_config_update:
        status: false
    # Adds used Block classes.
    block_class.settings:
      simple_config_update:
        block_classes_stored: '{"col":"col","col-3":"col-3","col-9":"col-9","col-12":"col-12","col-md-3":"col-md-3","col-md-9":"col-md-9"}'
    # Set the default theme.
    system.theme:
      simple_config_update:
        default: saplings_child
    # Allow anon to access patterns page.
    user.role.anonymous:
      ensure_exists:
        id: anonymous
      grantPermissions:
        - 'access patterns page'
